### ISSUE TITLE
Question about full code

### ISSUE THREAD

**Issue by sukzoon1234** [Malefikus/ada-depth#1]
Dear Authors,

Thanks for the good work. 
Could you please let me know when the full code will be released?

Thanks.

**Comment by Malefikus** [comment]
Hi,

As we are currently applying a patent based on the work, according to the restrictions of the collaborating company, we have to wait until the result of the patent comes out. Currently I’m really not sure about the exact date that I can put the code online. However, the code is ready and I will push it once I am allowed to.

Thanks for your understanding!

Regards,
Zhi

On 25. Jan 2024, at 15:39, sukzoon1234 ***@***.***> wrote:



Dear Authors,

Thanks for the good work.
Could you please let me know when the full code will be released?

Thanks.

**Comment by sukzoon1234** [comment]
Thanks for your kindness and quick reply!
