### ISSUE TITLE
Source models

### ISSUE THREAD

**Issue by dmn-sjk** [Malefikus/ada-depth#3]
Hello, could you share the trained checkpoints of the source models you used? It would help significantly.

**Comment by Malefikus** [comment]
Hi, as it was very long ago I forgot the exact settings but I uploaded the checkpoints from my disk, you can check which you need (I think the names are self-explanatory: xx_sup are the supervised source models and xx_unsup are the self-supervised). In case of any questions feel free to ask me (then I can be reminded what which part is doing).

Here is the link:
https://drive.google.com/file/d/1y2XXWqKMRZ_wRJC5XHKiYMae-OTPrqaT/view?usp=sharing

**Comment by dmn-sjk** [comment]
Thank you so much, I managed to reproduce the results on DDAD. Btw, it might be useful for others to mention in README that the DGP tool for the DDAD dataset should be version 0.1, as newer ones don't have `get_datum_index_for_datum_name` function.

**Comment by Malefikus** [comment]
> Thank you so much, I managed to reproduce the results on DDAD. Btw, it might be useful for others to mention in README that the DGP tool for the DDAD dataset should be version 0.1, as newer ones don't have `get_datum_index_for_datum_name` function.

Thanks a lot!! Just updated readme.
